# Generated by Django 5.0 on 2023-12-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appInvistaMe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investimento",
            name="nivel",
            field=models.IntegerField(default=1),
        ),
    ]
