# Generated by Django 5.0 on 2023-12-18 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appInvistaMe", "0002_investimento_nivel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investimento",
            name="nivel",
        ),
    ]
